apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helx-search.fullname" . }}-tranql-configmap
  labels:
    {{- include "helx-search.labels" . | nindent 4 }}
data:
  conf.yml: |
    m: z
  schema.yml: |
    doc: |
      Schema configuration for tranql
    schema:
      redis:
        doc: |
          helx-search is a knowledge graph built by aggregeting several kgx formatted knowledge graphs from several sources.
        url: "redis:"
        redis: true
        redis_connection_params:
          host: {{ .Release.Name }}-redis-master
          port: "6379"
          # SET USERNAME and PASSWORD
          # via helx-search_USERNAME , helx-search_PASSWORD Env vars (i.e capitialize service name)
