apiVersion: v1
kind: Service
metadata:
  {{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations }}
  {{- end }}
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: search-client-port
      protocol: TCP
      port: {{ .Values.http_port }}
      targetPort: {{ .Values.container_port }}
  selector:
    app: {{ .Values.app_name }}
  type: ClusterIP